# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    config.vm.network "public_network"
    config.vm.network "private_network",ip: "192.168.56.10", virtualbox__intnet: "vboxnet0"
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.define "localhost" do |l|
        l.vm.hostname = "localhost"

	l.vm.provision "ansible" do |ansible|
       		ansible.sudo = true
       		ansible.playbook = "servicios.yml"
        	ansible.verbose = "v"
        	ansible.host_key_checking = false
	end
    end



    config.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['ACCESS_KEY_ID']
        aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
        aws.keypair_name = ENV['PRIVATE_KEY_NAME']
        aws.ami = "ami-1c4a046f"
        aws.region = "eu-west-1"
        aws.security_groups = ENV['SECURITY_GROUP']
        aws.instance_type = "t2.micro"
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = ENV['PRIVATE_KEY_PATH']
    end
end
