- hosts: all
  become: yes
  remote_user: ubuntu
  become_method: sudo

  tasks:
  - name: Actualizar sistema base
    shell: apt-get update
  - name: Instalar docker
    shell: apt-get -y install docker.io
  - name: Descargar docker Gestion de la aplicación
    shell: sudo docker pull pmmre/cineforyou-gestion:Gestion
  - name: Ejecutar el contenedor
    shell: docker run -itd pmmre/cineforyou-gestion:Gestion
