# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.

  config.vm.box = "dummy"
  config.vm.synced_folder ".", "/vagrant", disabled: true



   config.vm.define :principal do |principal|
     principal.vm.host_name = "principal"

     principal.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['ACCESS_KEY_ID']
        aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
        aws.region = "eu-west-1"
        #aws.availability_zone = "eu-west-1a"

        # AMI from which we'll launch EC2 Instance
        aws.ami =  "ami-1c4a046f" # Ubuntu 16.04.1
        aws.keypair_name = ENV['PRIVATE_KEY_NAME']
        aws.instance_type = "t2.micro"
        aws.security_groups = [ENV['SECURITY_GROUP']]
        aws.tags = {
   		'Name' => 'CineForYou principal Instance',
   		'Environment' => 'vagrant-sandbox'
   		}
       # Credentials to login to EC2 Instance
       override.ssh.username = "ubuntu"
       override.ssh.private_key_path = ENV['PRIVATE_KEY_PATH']


     end

     #Provisioners configuration
     #principal.vm.provision :shell, :path => "installPythonUbuntu16.sh"
     #principal.vm.provision :ansible do |ansible|
     #   ansible.playbook = "principalPlaybook.yml"
#	ansible.verbose = "v"
#     end
   end

   config.vm.define :gestion do |gestion|
     gestion.vm.host_name = "gestion"

     gestion.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['ACCESS_KEY_ID']
        aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
        aws.region = "eu-west-1"
        #aws.availability_zone = "eu-west-1a"

        # AMI from which we'll launch EC2 Instance
        aws.ami =  "ami-1c4a046f" # Ubuntu 16.04.1
        aws.keypair_name = ENV['PRIVATE_KEY_NAME']
        aws.instance_type = "t2.micro"
        aws.security_groups = [ENV['SECURITY_GROUP']]
        aws.tags = {
      'Name' => 'CineForYou gestion Instance',
      'Environment' => 'vagrant-sandbox'
      }
       # Credentials to login to EC2 Instance
       override.ssh.username = "ubuntu"
       override.ssh.private_key_path = ENV['PRIVATE_KEY_PATH']


     end

     #Provisioners configuration
     #gestion.vm.provision :shell, :path => "installPythonUbuntu16.sh"
     gestion.vm.provision :ansible do |ansible|
        ansible.playbook = "gestionPlaybook.yml"
	ansible.verbose = "v"
     end
   end

   config.vm.define :mineria do |mineria|
     mineria.vm.host_name = "mineria"

     mineria.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['ACCESS_KEY_ID']
        aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
        aws.region = "eu-west-1"
        #aws.availability_zone = "eu-west-1a"

        # AMI from which we'll launch EC2 Instance
        aws.ami =  "ami-1c4a046f" # Ubuntu 16.04.1
        aws.keypair_name = ENV['PRIVATE_KEY_NAME']
        aws.instance_type = "t2.micro"
        aws.security_groups = [ENV['SECURITY_GROUP']]
        aws.tags = {
      'Name' => 'CineForYou mineria Instance',
      'Environment' => 'vagrant-sandbox'
      }
       # Credentials to login to EC2 Instance
       override.ssh.username = "ubuntu"
       override.ssh.private_key_path = ENV['PRIVATE_KEY_PATH']


     end

     #Provisioners configuration
     #mineria.vm.provision :shell, :path => "installPythonUbuntu16.sh"
     mineria.vm.provision :ansible do |ansible|
        ansible.playbook = "mineriaPlaybook.yml"
	ansible.verbose = "v"
     end
   end
end
